# Application Name
spring.application.name=step11-redis

# Server Configuration
server.port=8080

# Redis Configuration
spring.data.redis.host=redis-19837.c340.ap-northeast-2-1.ec2.cloud.redislabs.com
spring.data.redis.client-name=default
spring.data.redis.password=NW6xrPgjYElZNmxnJUtSGuCzZ6PtbAl8
spring.data.redis.port=19837
spring.data.redis.timeout=2000
## 동시에 사용할 수 있는 최대 연결 수 (기본 커넥션 풀 크기)
spring.data.redis.lettuce.pool.max-active=8
## 풀에 유지될 수 있는 최대 유휴 연결 수
spring.data.redis.lettuce.pool.max-idle=8
## 풀에 유지될 최소 유휴 연결 수
spring.data.redis.lettuce.pool.min-idle=0
## 연결 풀에서 커넥션을 빌릴 때 최대 대기 시간 (밀리초)
spring.data.redis.lettuce.pool.max-wait=-1

# Logging Configuration
logging.level.root=INFO
logging.level.io.lettuce.core=DEBUG
logging.level.org.springframework.data.redis=DEBUG
