spring.application.name=step08-rest-api-exception

# DB
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/scott?serverTimezone=Asia/Seoul
spring.datasource.username=scott
spring.datasource.password=tiger

# JPA
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

# Thymeleaf Settings
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html